name: Docker Image build and push

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build ./docker-project -t anilsrana07/aniltest:${{ github.run_number }}
          docker tag anilsrana07/aniltest:${{ github.run_number }} anilsrana07/aniltest:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push anilsrana07/aniltest:${{ github.run_number }}
          docker push anilsrana07/aniltest:latest
