name: Docker Image build and push 

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build Image
        run: docker build ./docker-project -t anilsrana07/aniltest:neelam
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: anilsrana07/aniltest
        run: docker push anilsrana07/aniltest:neelam
